<?php
/**
 * BRERuleEngineTriggersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KnetikCloud;

use \KnetikCloud\Configuration;
use \KnetikCloud\ApiClient;
use \KnetikCloud\ApiException;
use \KnetikCloud\ObjectSerializer;

/**
 * BRERuleEngineTriggersApiTest Class Doc Comment
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BRERuleEngineTriggersApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createBRETrigger
     *
     * Create a trigger.
     *
     */
    public function testCreateBRETrigger()
    {

    }

    /**
     * Test case for deleteBRETrigger
     *
     * Delete a trigger.
     *
     */
    public function testDeleteBRETrigger()
    {

    }

    /**
     * Test case for getBRETrigger
     *
     * Get a single trigger.
     *
     */
    public function testGetBRETrigger()
    {

    }

    /**
     * Test case for getBRETriggers
     *
     * List triggers.
     *
     */
    public function testGetBRETriggers()
    {

    }

    /**
     * Test case for updateBRETrigger
     *
     * Update a trigger.
     *
     */
    public function testUpdateBRETrigger()
    {

    }

}
