<?php
/**
 * ReportingRevenueApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KnetikCloud;

use \KnetikCloud\Configuration;
use \KnetikCloud\ApiException;
use \KnetikCloud\ObjectSerializer;

/**
 * ReportingRevenueApiTest Class Doc Comment
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReportingRevenueApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getItemRevenue
     *
     * Get item revenue info.
     *
     */
    public function testGetItemRevenue()
    {
    }

    /**
     * Test case for getRefundRevenue
     *
     * Get refund revenue info.
     *
     */
    public function testGetRefundRevenue()
    {
    }

    /**
     * Test case for getRevenueByCountry
     *
     * Get revenue info by country.
     *
     */
    public function testGetRevenueByCountry()
    {
    }

    /**
     * Test case for getRevenueByItem
     *
     * Get revenue info by item.
     *
     */
    public function testGetRevenueByItem()
    {
    }

    /**
     * Test case for getSubscriptionRevenue
     *
     * Get subscription revenue info.
     *
     */
    public function testGetSubscriptionRevenue()
    {
    }
}
