<?php
/**
 * Store_Shopping_CartsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KnetikCloud;

use \KnetikCloud\Configuration;
use \KnetikCloud\ApiException;
use \KnetikCloud\ObjectSerializer;

/**
 * Store_Shopping_CartsApiTest Class Doc Comment
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Store_Shopping_CartsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addCustomDiscount
     *
     * Adds a custom discount to the cart.
     *
     */
    public function testAddCustomDiscount()
    {
    }

    /**
     * Test case for addDiscountToCart
     *
     * Adds a discount coupon to the cart.
     *
     */
    public function testAddDiscountToCart()
    {
    }

    /**
     * Test case for addItemToCart
     *
     * Add an item to the cart.
     *
     */
    public function testAddItemToCart()
    {
    }

    /**
     * Test case for createCart
     *
     * Create a cart.
     *
     */
    public function testCreateCart()
    {
    }

    /**
     * Test case for getCart
     *
     * Returns the cart with the given GUID.
     *
     */
    public function testGetCart()
    {
    }

    /**
     * Test case for getCarts
     *
     * Get a list of carts.
     *
     */
    public function testGetCarts()
    {
    }

    /**
     * Test case for getShippable
     *
     * Returns whether a cart requires shipping.
     *
     */
    public function testGetShippable()
    {
    }

    /**
     * Test case for getShippingCountries
     *
     * Get the list of available shipping countries per vendor.
     *
     */
    public function testGetShippingCountries()
    {
    }

    /**
     * Test case for removeDiscountFromCart
     *
     * Removes a discount coupon from the cart.
     *
     */
    public function testRemoveDiscountFromCart()
    {
    }

    /**
     * Test case for setCartCurrency
     *
     * Sets the currency to use for the cart.
     *
     */
    public function testSetCartCurrency()
    {
    }

    /**
     * Test case for setCartOwner
     *
     * Sets the owner of a cart if none is set already.
     *
     */
    public function testSetCartOwner()
    {
    }

    /**
     * Test case for updateItemInCart
     *
     * Changes the quantity of an item already in the cart.
     *
     */
    public function testUpdateItemInCart()
    {
    }

    /**
     * Test case for updateShippingAddress
     *
     * Modifies or sets the order shipping address.
     *
     */
    public function testUpdateShippingAddress()
    {
    }
}
