<?php
/**
 * Store_BundlesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace KnetikCloud;

use \KnetikCloud\Configuration;
use \KnetikCloud\ApiException;
use \KnetikCloud\ObjectSerializer;

/**
 * Store_BundlesApiTest Class Doc Comment
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Store_BundlesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createBundleItem
     *
     * Create a bundle item.
     *
     */
    public function testCreateBundleItem()
    {
    }

    /**
     * Test case for createBundleTemplate
     *
     * Create a bundle template.
     *
     */
    public function testCreateBundleTemplate()
    {
    }

    /**
     * Test case for deleteBundleItem
     *
     * Delete a bundle item.
     *
     */
    public function testDeleteBundleItem()
    {
    }

    /**
     * Test case for deleteBundleTemplate
     *
     * Delete a bundle template.
     *
     */
    public function testDeleteBundleTemplate()
    {
    }

    /**
     * Test case for getBundleItem
     *
     * Get a single bundle item.
     *
     */
    public function testGetBundleItem()
    {
    }

    /**
     * Test case for getBundleTemplate
     *
     * Get a single bundle template.
     *
     */
    public function testGetBundleTemplate()
    {
    }

    /**
     * Test case for getBundleTemplates
     *
     * List and search bundle templates.
     *
     */
    public function testGetBundleTemplates()
    {
    }

    /**
     * Test case for updateBundleItem
     *
     * Update a bundle item.
     *
     */
    public function testUpdateBundleItem()
    {
    }

    /**
     * Test case for updateBundleTemplate
     *
     * Update a bundle template.
     *
     */
    public function testUpdateBundleTemplate()
    {
    }
}
