<?php
/**
 * Group
 *
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace KnetikCloud\Model;

use \ArrayAccess;

/**
 * Group Class Doc Comment
 *
 * @category    Class
 * @package     KnetikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Group implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Group';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'additional_properties' => 'map[string,\KnetikCloud\Model\Property]',
        'description' => 'string',
        'id' => 'int',
        'member_count' => 'int',
        'message_of_the_day' => 'string',
        'name' => 'string',
        'parent' => '\KnetikCloud\Model\Group',
        'properties_string' => 'string',
        'status' => 'string',
        'sub_member_count' => 'int',
        'template' => 'string',
        'unique_name' => 'string'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'additional_properties' => 'additional_properties',
        'description' => 'description',
        'id' => 'id',
        'member_count' => 'member_count',
        'message_of_the_day' => 'message_of_the_day',
        'name' => 'name',
        'parent' => 'parent',
        'properties_string' => 'properties_string',
        'status' => 'status',
        'sub_member_count' => 'sub_member_count',
        'template' => 'template',
        'unique_name' => 'unique_name'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'additional_properties' => 'setAdditionalProperties',
        'description' => 'setDescription',
        'id' => 'setId',
        'member_count' => 'setMemberCount',
        'message_of_the_day' => 'setMessageOfTheDay',
        'name' => 'setName',
        'parent' => 'setParent',
        'properties_string' => 'setPropertiesString',
        'status' => 'setStatus',
        'sub_member_count' => 'setSubMemberCount',
        'template' => 'setTemplate',
        'unique_name' => 'setUniqueName'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'additional_properties' => 'getAdditionalProperties',
        'description' => 'getDescription',
        'id' => 'getId',
        'member_count' => 'getMemberCount',
        'message_of_the_day' => 'getMessageOfTheDay',
        'name' => 'getName',
        'parent' => 'getParent',
        'properties_string' => 'getPropertiesString',
        'status' => 'getStatus',
        'sub_member_count' => 'getSubMemberCount',
        'template' => 'getTemplate',
        'unique_name' => 'getUniqueName'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const STATUS_OPEN = 'open';
    const STATUS_CLOSED = 'closed';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_OPEN,
            self::STATUS_CLOSED,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['additional_properties'] = isset($data['additional_properties']) ? $data['additional_properties'] : null;
        $this->container['description'] = isset($data['description']) ? $data['description'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['member_count'] = isset($data['member_count']) ? $data['member_count'] : null;
        $this->container['message_of_the_day'] = isset($data['message_of_the_day']) ? $data['message_of_the_day'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['parent'] = isset($data['parent']) ? $data['parent'] : null;
        $this->container['properties_string'] = isset($data['properties_string']) ? $data['properties_string'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['sub_member_count'] = isset($data['sub_member_count']) ? $data['sub_member_count'] : null;
        $this->container['template'] = isset($data['template']) ? $data['template'] : null;
        $this->container['unique_name'] = isset($data['unique_name']) ? $data['unique_name'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        $allowed_values = ["open", "closed"];
        if (!in_array($this->container['status'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'status', must be one of 'open', 'closed'.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        $allowed_values = ["open", "closed"];
        if (!in_array($this->container['status'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets additional_properties
     * @return map[string,\KnetikCloud\Model\Property]
     */
    public function getAdditionalProperties()
    {
        return $this->container['additional_properties'];
    }

    /**
     * Sets additional_properties
     * @param map[string,\KnetikCloud\Model\Property] $additional_properties
     * @return $this
     */
    public function setAdditionalProperties($additional_properties)
    {
        $this->container['additional_properties'] = $additional_properties;

        return $this;
    }

    /**
     * Gets description
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets member_count
     * @return int
     */
    public function getMemberCount()
    {
        return $this->container['member_count'];
    }

    /**
     * Sets member_count
     * @param int $member_count
     * @return $this
     */
    public function setMemberCount($member_count)
    {
        $this->container['member_count'] = $member_count;

        return $this;
    }

    /**
     * Gets message_of_the_day
     * @return string
     */
    public function getMessageOfTheDay()
    {
        return $this->container['message_of_the_day'];
    }

    /**
     * Sets message_of_the_day
     * @param string $message_of_the_day
     * @return $this
     */
    public function setMessageOfTheDay($message_of_the_day)
    {
        $this->container['message_of_the_day'] = $message_of_the_day;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets parent
     * @return \KnetikCloud\Model\Group
     */
    public function getParent()
    {
        return $this->container['parent'];
    }

    /**
     * Sets parent
     * @param \KnetikCloud\Model\Group $parent
     * @return $this
     */
    public function setParent($parent)
    {
        $this->container['parent'] = $parent;

        return $this;
    }

    /**
     * Gets properties_string
     * @return string
     */
    public function getPropertiesString()
    {
        return $this->container['properties_string'];
    }

    /**
     * Sets properties_string
     * @param string $properties_string
     * @return $this
     */
    public function setPropertiesString($properties_string)
    {
        $this->container['properties_string'] = $properties_string;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status
     * @return $this
     */
    public function setStatus($status)
    {
        $allowed_values = array('open', 'closed');
        if (!is_null($status) && (!in_array($status, $allowed_values))) {
            throw new \InvalidArgumentException("Invalid value for 'status', must be one of 'open', 'closed'");
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets sub_member_count
     * @return int
     */
    public function getSubMemberCount()
    {
        return $this->container['sub_member_count'];
    }

    /**
     * Sets sub_member_count
     * @param int $sub_member_count
     * @return $this
     */
    public function setSubMemberCount($sub_member_count)
    {
        $this->container['sub_member_count'] = $sub_member_count;

        return $this;
    }

    /**
     * Gets template
     * @return string
     */
    public function getTemplate()
    {
        return $this->container['template'];
    }

    /**
     * Sets template
     * @param string $template
     * @return $this
     */
    public function setTemplate($template)
    {
        $this->container['template'] = $template;

        return $this;
    }

    /**
     * Gets unique_name
     * @return string
     */
    public function getUniqueName()
    {
        return $this->container['unique_name'];
    }

    /**
     * Sets unique_name
     * @param string $unique_name
     * @return $this
     */
    public function setUniqueName($unique_name)
    {
        $this->container['unique_name'] = $unique_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\KnetikCloud\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\KnetikCloud\ObjectSerializer::sanitizeForSerialization($this));
    }
}


