<?php
/**
 * OrderTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KnetikCloud;

/**
 * OrderTest Class Doc Comment
 *
 * @category    Class */
// * @description Order
/**
 * @package     KnetikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Order"
     */
    public function testOrder()
    {

    }

    /**
     * Test attribute "ascending"
     */
    public function testPropertyAscending()
    {

    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {

    }

    /**
     * Test attribute "ignore_case"
     */
    public function testPropertyIgnoreCase()
    {

    }

    /**
     * Test attribute "null_handling"
     */
    public function testPropertyNullHandling()
    {

    }

    /**
     * Test attribute "property"
     */
    public function testPropertyProperty()
    {

    }

}
