<?php
/**
 * StateTaxResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KnetikCloud;

/**
 * StateTaxResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description StateTaxResource
/**
 * @package     KnetikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StateTaxResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StateTaxResource"
     */
    public function testStateTaxResource()
    {
    }

    /**
     * Test attribute "country_iso3"
     */
    public function testPropertyCountryIso3()
    {
    }

    /**
     * Test attribute "federally_exempt"
     */
    public function testPropertyFederallyExempt()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "rate"
     */
    public function testPropertyRate()
    {
    }

    /**
     * Test attribute "state_code"
     */
    public function testPropertyStateCode()
    {
    }

    /**
     * Test attribute "tax_shipping"
     */
    public function testPropertyTaxShipping()
    {
    }
}
