<?php
/**
 * TheDefinitionOfAnActivityParametersExDifficultyLevelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KnetikCloud;

/**
 * TheDefinitionOfAnActivityParametersExDifficultyLevelTest Class Doc Comment
 *
 * @category    Class */
// * @description TheDefinitionOfAnActivityParametersExDifficultyLevel
/**
 * @package     KnetikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TheDefinitionOfAnActivityParametersExDifficultyLevelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "TheDefinitionOfAnActivityParametersExDifficultyLevel"
     */
    public function testTheDefinitionOfAnActivityParametersExDifficultyLevel()
    {

    }

    /**
     * Test attribute "advanced_option"
     */
    public function testPropertyAdvancedOption()
    {

    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "key"
     */
    public function testPropertyKey()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {

    }

}
