<?php
/**
 * VendorResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  KnetikCloud
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Knetik Platform API Documentation latest
 *
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest
 * Contact: support@knetik.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace KnetikCloud;

/**
 * VendorResourceTest Class Doc Comment
 *
 * @category    Class */
// * @description VendorResource
/**
 * @package     KnetikCloud
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VendorResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "VendorResource"
     */
    public function testVendorResource()
    {

    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {

    }

    /**
     * Test attribute "additional_properties"
     */
    public function testPropertyAdditionalProperties()
    {

    }

    /**
     * Test attribute "create_date"
     */
    public function testPropertyCreateDate()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "image_url"
     */
    public function testPropertyImageUrl()
    {

    }

    /**
     * Test attribute "manual_approval"
     */
    public function testPropertyManualApproval()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "primary_contact_email"
     */
    public function testPropertyPrimaryContactEmail()
    {

    }

    /**
     * Test attribute "primary_contact_name"
     */
    public function testPropertyPrimaryContactName()
    {

    }

    /**
     * Test attribute "primary_contact_phone"
     */
    public function testPropertyPrimaryContactPhone()
    {

    }

    /**
     * Test attribute "sales_email"
     */
    public function testPropertySalesEmail()
    {

    }

    /**
     * Test attribute "support_email"
     */
    public function testPropertySupportEmail()
    {

    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {

    }

    /**
     * Test attribute "update_date"
     */
    public function testPropertyUpdateDate()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

}
